name: helmfile-and-yq

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up yq
        uses: frenck/action-setup-yq@v1
      -
        name: Set up helmfile
        uses: helmfile/helmfile-action@v1.0.0
      - 
        name: test tools
        run: |
          yq --help
          helmfile --help

